---
# Source: mq-metric-samples/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-metric-samples
data:
  IBMMQ_CONNECTION_QUEUEMANAGER: "QM1"
  IBMMQ_CONNECTION_CONNNAME: "qm1-ibm-mq.dev.svc.cluster.local(1414)"
  IBMMQ_CONNECTION_CHANNEL: "MONITORING_CHL"
  IBMMQ_OBJECTS_QUEUES: "!SYSTEM.*,!AMQ.*,*"
  IBMMQ_OBJECTS_SUBSCRIPTIONS: "!$SYS*"
  IBMMQ_OBJECTS_TOPICS: "!*"
  IBMMQ_GLOBAL_USEPUBLICATIONS: "false"
  IBMMQ_GLOBAL_USEOBJECTSTATUS: "true"
  IBMMQ_GLOBAL_CONFIGURATIONFILE: ""
  IBMMQ_GLOBAL_LOGLEVEL: "INFO"
